environment:
  matrix:
    - nodejs_version: '12'
    - nodejs_version: '10'
    - nodejs_version: '8'
    - nodejs_version: '6'
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install --global npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install
build: off
test_script:
  - node --version
  - npm --version
  - npm install -g mocha
  - npm test
cache:
  - '%APPDATA%\npm-cache'
